name: AutoQNDXX

on:
  schedule:
    # Run at 8:00 on every Tuesday.
    - cron: '0 0  * * 2'

  push:
    
  workflow_dispatch:

jobs:
  # build:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip' # caching pip dependencies

      
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - run: pip install -r requirements.txt

      - name: 'Working'
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          ORG_ID: ${{secrets.ORG_ID}}
          REMOTE_CONFIG: ${{secrets.REMOTE_CONFIG}}
        run: |
          python main.py
      

      - name: Converts Markdown to HTML
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: html/index.md
          output: html/index.html

      - name: CNAME
        runs: |
          echo 'qndxx.tk' > ./html/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
      # - name: Setup Pages
      #   uses: actions/configure-pages@v2
      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v1
      #   with:
      #     # Upload entire repository
      #     path: './html'
      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v1
        